//! OSM entity types.

use std::collections::HashMap;
use std::sync::OnceLock;

/// Get a map with all known entity types and their human-readable names.
pub fn entity_types() -> &'static HashMap<&'static str, &'static str> {
    static ENTITY_TYPES: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    ENTITY_TYPES.get_or_init(|| {
        let mut entity_types = HashMap::new();
        for (tag, name) in TUPLES {
            entity_types.insert(tag, name);
        }
        entity_types
    })
}

/// List of OSM tuples based on:
/// <https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml>
static TUPLES: [(&str, &str); 754] = [
    ("aerialway", "Aerialway"),
    ("aerialway_cable_car", "Cable Car"),
    ("aerialway_chair_lift", "Chair Lift"),
    ("aerialway_drag_lift", "Drag Lift"),
    ("aerialway_gondola", "Gondola Lift"),
    ("aerialway_magic_carpet", "Magic Carpet Lift"),
    ("aerialway_platter", "Platter Lift"),
    ("aerialway_pylon", "Pylon"),
    ("aerialway_station", "Aerialway Station"),
    ("aerialway_t-bar", "T-Bar Lift"),
    ("aeroway_aerodrome", "Aerodrome"),
    ("aeroway_airstrip", "Airstrip"),
    ("aeroway_apron", "Airport Apron"),
    ("aeroway_gate", "Airport Gate"),
    ("aeroway_hangar", "Hangar"),
    ("aeroway_helipad", "Helipad"),
    ("aeroway_holding_position", "Holding Position"),
    ("aeroway_navigationaid", "Aviation Navigation Aid"),
    ("aeroway_parking_position", "Parking Position"),
    ("aeroway_runway", "Runway"),
    ("aeroway_taxilane", "Taxilane"),
    ("aeroway_taxiway", "Taxiway"),
    ("aeroway_terminal", "Airport Terminal"),
    ("aeroway_windsock", "Windsock"),
    ("amenity", "Amenity"),
    ("amenity_animal_boarding", "Animal Boarding"),
    ("amenity_animal_shelter", "Animal Shelter"),
    ("amenity_arts_centre", "Arts Centre"),
    ("amenity_atm", "ATM"),
    ("amenity_bank", "Bank"),
    ("amenity_bar", "Bar"),
    ("amenity_bbq", "BBQ"),
    ("amenity_bench", "Bench"),
    ("amenity_bicycle_parking", "Cycle Parking"),
    ("amenity_bicycle_rental", "Cycle Rental"),
    ("amenity_bicycle_repair_station", "Bicycle Repair Station"),
    ("amenity_biergarten", "Beer Garden"),
    ("amenity_blood_bank", "Blood Bank"),
    ("amenity_boat_rental", "Boat Rental"),
    ("amenity_brothel", "Brothel"),
    ("amenity_bureau_de_change", "Bureau de Change"),
    ("amenity_bus_station", "Bus Station"),
    ("amenity_cafe", "Cafe"),
    ("amenity_car_rental", "Car Rental"),
    ("amenity_car_sharing", "Car Sharing"),
    ("amenity_car_wash", "Car Wash"),
    ("amenity_casino", "Casino"),
    ("amenity_charging_station", "Charging Station"),
    ("amenity_childcare", "Childcare"),
    ("amenity_cinema", "Cinema"),
    ("amenity_clinic", "Clinic"),
    ("amenity_clock", "Clock"),
    ("amenity_college", "College"),
    ("amenity_community_centre", "Community Centre"),
    ("amenity_conference_centre", "Conference Centre"),
    ("amenity_courthouse", "Courthouse"),
    ("amenity_crematorium", "Crematorium"),
    ("amenity_dentist", "Dentist"),
    ("amenity_doctors", "Doctors"),
    ("amenity_drinking_water", "Drinking Water"),
    ("amenity_driving_school", "Driving School"),
    ("amenity_embassy", "Embassy"),
    ("amenity_events_venue", "Events Venue"),
    ("amenity_fast_food", "Fast Food"),
    ("amenity_ferry_terminal", "Ferry Terminal"),
    ("amenity_fire_station", "Fire Station"),
    ("amenity_food_court", "Food Court"),
    ("amenity_fountain", "Fountain"),
    ("amenity_fuel", "Filling Station"),
    ("amenity_gambling", "Gambling"),
    ("amenity_grave_yard", "Grave Yard"),
    ("amenity_grit_bin", "Grit Bin"),
    ("amenity_hospital", "Hospital"),
    ("amenity_hunting_stand", "Hunting Stand"),
    ("amenity_ice_cream", "Ice Cream"),
    ("amenity_internet_cafe", "Internet Cafe"),
    ("amenity_kindergarten", "Kindergarten"),
    ("amenity_language_school", "Language School"),
    ("amenity_library", "Library"),
    ("amenity_loading_dock", "Loading Dock"),
    ("amenity_love_hotel", "Love Hotel"),
    ("amenity_marketplace", "Marketplace"),
    ("amenity_mobile_money_agent", "Mobile Money Agent"),
    ("amenity_monastery", "Monastery"),
    ("amenity_money_transfer", "Money Transfer"),
    ("amenity_motorcycle_parking", "Motorcycle Parking"),
    ("amenity_music_school", "Music School"),
    ("amenity_nightclub", "Night Club"),
    ("amenity_nursing_home", "Nursing Home"),
    ("amenity_parking_entrance", "Parking Entrance"),
    ("amenity_parking", "Parking"),
    ("amenity_parking_space", "Parking Space"),
    ("amenity_payment_terminal", "Payment Terminal"),
    ("amenity_pharmacy", "Pharmacy"),
    ("amenity_place_of_worship", "Place of Worship"),
    ("amenity_police", "Police"),
    ("amenity_post_box", "Post Box"),
    ("amenity_post_office", "Post Office"),
    ("amenity_prison", "Prison"),
    ("amenity_public_bath", "Public Bath"),
    ("amenity_public_bookcase", "Public Bookcase"),
    ("amenity_public_building", "Public Building"),
    ("amenity_pub", "Pub"),
    ("amenity_ranger_station", "Ranger Station"),
    ("amenity_recycling", "Recycling Point"),
    ("amenity_restaurant", "Restaurant"),
    ("amenity_sanitary_dump_station", "Sanitary Dump Station"),
    ("amenity_school", "School"),
    ("amenity_shelter", "Shelter"),
    ("amenity_shower", "Shower"),
    ("amenity_social_centre", "Social Centre"),
    ("amenity_social_facility", "Social Facility"),
    ("amenity_studio", "Studio"),
    ("amenity_swimming_pool", "Swimming Pool"),
    ("amenity_taxi", "Taxi"),
    ("amenity_telephone", "Public Telephone"),
    ("amenity_theatre", "Theatre"),
    ("amenity_toilets", "Toilets"),
    ("amenity_townhall", "Town Hall"),
    ("amenity_training", "Training Facility"),
    ("amenity_university", "University"),
    ("amenity_vehicle_inspection", "Vehicle Inspection"),
    ("amenity_vending_machine", "Vending Machine"),
    ("amenity_veterinary", "Veterinary Surgery"),
    ("amenity_village_hall", "Village Hall"),
    ("amenity_waste_basket", "Waste Basket"),
    ("amenity_waste_disposal", "Waste Disposal"),
    ("amenity_waste_dump_site", "Waste Dump Site"),
    ("amenity_watering_place", "Watering Place"),
    ("amenity_water_point", "Water Point"),
    ("amenity_weighbridge", "Weighbridge"),
    ("boundary_aboriginal_lands", "Aboriginal Lands"),
    ("boundary_administrative", "Administrative Boundary"),
    ("boundary", "Boundary"),
    ("boundary_census", "Census Boundary"),
    ("boundary_national_park", "National Park"),
    ("boundary_political", "Electoral Boundary"),
    ("boundary_protected_area", "Protected Area"),
    ("bridge_aqueduct", "Aqueduct"),
    ("bridge_boardwalk", "Boardwalk"),
    ("bridge", "Bridge"),
    ("bridge_suspension", "Suspension Bridge"),
    ("bridge_swing", "Swing Bridge"),
    ("bridge_viaduct", "Viaduct"),
    ("building_apartment", "Apartment"),
    ("building_apartments", "Apartments"),
    ("building_barn", "Barn"),
    ("building", "Building"),
    ("building_bungalow", "Bungalow"),
    ("building_cabin", "Cabin"),
    ("building_chapel", "Chapel"),
    ("building_church", "Church Building"),
    ("building_civic", "Civic Building"),
    ("building_college", "College Building"),
    ("building_commercial", "Commercial Building"),
    ("building_construction", "Building under Construction"),
    ("building_cowshed", "Cowshed"),
    ("building_detached", "Detached House"),
    ("building_dormitory", "Dormitory"),
    ("building_duplex", "Duplex House"),
    ("building_farm_auxiliary", "Auxiliary Farm House"),
    ("building_farm", "Farm House"),
    ("building_garage", "Garage"),
    ("building_garages", "Garages"),
    ("building_greenhouse", "Greenhouse"),
    ("building_hangar", "Hangar"),
    ("building_hospital", "Hospital Building"),
    ("building_hotel", "Hotel Building"),
    ("building_houseboat", "Houseboat"),
    ("building_house", "House"),
    ("building_hut", "Hut"),
    ("building_industrial", "Industrial Building"),
    ("building_kindergarten", "Kindergarten Building"),
    ("building_manufacture", "Manufacturing Building"),
    ("building_office", "Office Building"),
    ("building_public", "Public Building"),
    ("building_residential", "Residential Building"),
    ("building_retail", "Retail Building"),
    ("building_roof", "Roof"),
    ("building_ruins", "Ruined Building"),
    ("building_school", "School Building"),
    ("building_semidetached_house", "Semidetached House"),
    ("building_service", "Service Building"),
    ("building_shed", "Shed"),
    ("building_stable", "Stable"),
    ("building_static_caravan", "Caravan"),
    ("building_sty", "Sty"),
    ("building_temple", "Temple Building"),
    ("building_terrace", "Terrace Building"),
    ("building_train_station", "Train Station Building"),
    ("building_university", "University Building"),
    ("building_warehouse", "Warehouse"),
    ("club", "Club"),
    ("club_scout", "Scout Group Base"),
    ("club_sport", "Sports Club"),
    ("craft_beekeeper", "Beekeeper"),
    ("craft_blacksmith", "Blacksmith"),
    ("craft_brewery", "Brewery"),
    ("craft_carpenter", "Carpenter"),
    ("craft_caterer", "Caterer"),
    ("craft_confectionery", "Confectionary"),
    ("craft", "Craft Shop"),
    ("craft_dressmaker", "Dressmaker"),
    ("craft_electrician", "Electrician"),
    ("craft_electronics_repair", "Electronics Repair"),
    ("craft_gardener", "Gardener"),
    ("craft_glaziery", "Glaziery"),
    ("craft_handicraft", "Handicraft"),
    ("craft_hvac", "HVAC Craft"),
    ("craft_metal_construction", "Metal Constructioner"),
    ("craft_painter", "Painter"),
    ("craft_photographer", "Photographer"),
    ("craft_plumber", "Plumber"),
    ("craft_roofer", "Roofer"),
    ("craft_sawmill", "Sawmill"),
    ("craft_shoemaker", "Shoemaker"),
    ("craft_stonemason", "Stonemason"),
    ("craft_tailor", "Tailor"),
    ("craft_window_construction", "Window Construction"),
    ("craft_winery", "Winery"),
    ("emergency_access_point", "Access Point"),
    ("emergency_ambulance_station", "Ambulance Station"),
    ("emergency_assembly_point", "Assembly Point"),
    ("emergency_defibrillator", "Defibrillator"),
    ("emergency_fire_extinguisher", "Fire Extinguisher"),
    ("emergency_fire_water_pond", "Fire Water Pond"),
    ("emergency_landing_site", "Emergency Landing Site"),
    ("emergency_life_ring", "Emergency Life Ring"),
    ("emergency_phone", "Emergency Phone"),
    ("emergency_siren", "Emergency Siren"),
    ("emergency_suction_point", "Emergency Suction Point"),
    ("emergency_water_tank", "Emergency Water Tank"),
    ("highway_abandoned", "Abandoned Highway"),
    ("highway_bridleway", "Bridleway"),
    ("highway_bus_guideway", "Guided Bus Lane"),
    ("highway_bus_stop", "Bus Stop"),
    ("highway_busway", "Busway"),
    ("highway_construction", "Highway under Construction"),
    ("highway_corridor", "Corridor"),
    ("highway_crossing", "Crossing"),
    ("highway_cycleway", "Cycle Path"),
    ("highway_elevator", "Elevator"),
    ("highway_emergency_access_point", "Emergency Access Point"),
    ("highway_emergency_bay", "Emergency Bay"),
    ("highway_footway", "Footpath"),
    ("highway_ford", "Ford"),
    ("highway_give_way", "Give Way Sign"),
    ("highway_living_street", "Living Street"),
    ("highway_milestone", "Milestone"),
    ("highway_motorway_junction", "Motorway Junction"),
    ("highway_motorway_link", "Motorway Road"),
    ("highway_motorway", "Motorway"),
    ("highway_passing_place", "Passing Place"),
    ("highway_path", "Path"),
    ("highway_pedestrian", "Pedestrian Way"),
    ("highway_platform", "Platform"),
    ("highway_primary_link", "Primary Road"),
    ("highway_primary", "Primary Road"),
    ("highway_proposed", "Proposed Road"),
    ("highway_raceway", "Raceway"),
    ("highway_residential", "Residential Road"),
    ("highway_rest_area", "Rest Area"),
    ("highway", "Road"),
    ("highway_road", "Road"),
    ("highway_secondary_link", "Secondary Road"),
    ("highway_secondary", "Secondary Road"),
    ("highway_service", "Service Road"),
    ("highway_services", "Motorway Services"),
    ("highway_speed_camera", "Speed Camera"),
    ("highway_steps", "Steps"),
    ("highway_stop", "Stop Sign"),
    ("highway_street_lamp", "Street Lamp"),
    ("highway_tertiary_link", "Tertiary Road"),
    ("highway_tertiary", "Tertiary Road"),
    ("highway_track", "Track"),
    ("highway_traffic_mirror", "Traffic Mirror"),
    ("highway_traffic_signals", "Traffic Signals"),
    ("highway_trailhead", "Trailhead"),
    ("highway_trunk_link", "Trunk Road"),
    ("highway_trunk", "Trunk Road"),
    ("highway_turning_circle", "Turning Circle"),
    ("highway_turning_loop", "Turning Loop"),
    ("highway_unclassified", "Unclassified Road"),
    ("historic_aircraft", "Historic Aircraft"),
    ("historic_archaeological_site", "Archaeological Site"),
    ("historic_battlefield", "Battlefield"),
    ("historic_bomb_crater", "Historic Bomb Crater"),
    ("historic_boundary_stone", "Boundary Stone"),
    ("historic_building", "Historic Building"),
    ("historic_bunker", "Bunker"),
    ("historic_cannon", "Historic Cannon"),
    ("historic_castle", "Castle"),
    ("historic_charcoal_pile", "Historic Charcoal Pile"),
    ("historic_church", "Church"),
    ("historic_city_gate", "City Gate"),
    ("historic_citywalls", "City Walls"),
    ("historic_fort", "Fort"),
    ("historic_heritage", "Heritage Site"),
    ("historic", "Historic Site"),
    ("historic_hollow_way", "Hollow Way"),
    ("historic_house", "House"),
    ("historic_manor", "Manor"),
    ("historic_memorial", "Memorial"),
    ("historic_milestone", "Historic Milestone"),
    ("historic_mine", "Mine"),
    ("historic_mine_shaft", "Mine Shaft"),
    ("historic_monument", "Monument"),
    ("historic_railway", "Historic Railway"),
    ("historic_roman_road", "Roman Road"),
    ("historic_ruins", "Ruins"),
    ("historic_rune_stone", "Rune Stone"),
    ("historic_stone", "Stone"),
    ("historic_tomb", "Tomb"),
    ("historic_tower", "Tower"),
    ("historic_wayside_chapel", "Wayside Chapel"),
    ("historic_wayside_cross", "Wayside Cross"),
    ("historic_wayside_shrine", "Wayside Shrine"),
    ("historic_wreck", "Wreck"),
    ("information_board", "Information Board"),
    ("information_guidepost", "Guidepost"),
    ("information_map", "Map"),
    ("information_office", "Tourist Office"),
    ("information_sign", "Information Sign"),
    ("information_stele", "Information Stele"),
    ("information_terminal", "Information Terminal"),
    ("junction", "Junction"),
    ("landuse_allotments", "Allotments"),
    ("landuse_aquaculture", "Aquaculture"),
    ("landuse_basin", "Basin"),
    ("landuse_brownfield", "Brownfield Land"),
    ("landuse_cemetery", "Cemetery"),
    ("landuse_commercial", "Commercial Area"),
    ("landuse_conservation", "Conservation Area"),
    ("landuse_construction", "Construction Area"),
    ("landuse_farmland", "Farmland"),
    ("landuse_farmyard", "Farmyard"),
    ("landuse_forest", "Forest"),
    ("landuse_garages", "Garages"),
    ("landuse_grass", "Grass"),
    ("landuse_greenfield", "Greenfield Land"),
    ("landuse_industrial", "Industrial Area"),
    ("landuse_landfill", "Landfill"),
    ("landuse", "Landuse"),
    ("landuse_meadow", "Meadow"),
    ("landuse_military", "Military Area"),
    ("landuse_mine", "Mine"),
    ("landuse_orchard", "Orchard"),
    ("landuse_plant_nursery", "Plant Nursery"),
    ("landuse_quarry", "Quarry"),
    ("landuse_railway", "Railway"),
    ("landuse_recreation_ground", "Recreation Ground"),
    ("landuse_religious", "Religious Ground"),
    ("landuse_reservoir", "Reservoir"),
    ("landuse_reservoir_watershed", "Reservoir Watershed"),
    ("landuse_residential", "Residential Area"),
    ("landuse_retail", "Retail Area"),
    ("landuse_village_green", "Village Green"),
    ("landuse_vineyard", "Vineyard"),
    ("leisure_adult_gaming_centre", "Adult Gaming Centre"),
    ("leisure_amusement_arcade", "Amusement Arcade"),
    ("leisure_bandstand", "Bandstand"),
    ("leisure_beach_resort", "Beach Resort"),
    ("leisure_bird_hide", "Bird Hide"),
    ("leisure_bleachers", "Bleachers"),
    ("leisure_bowling_alley", "Bowling Alley"),
    ("leisure_common", "Common Land"),
    ("leisure_dance", "Dance Hall"),
    ("leisure_dog_park", "Dog Park"),
    ("leisure_firepit", "Fire Pit"),
    ("leisure_fishing", "Fishing Area"),
    ("leisure_fitness_centre", "Fitness Centre"),
    ("leisure_fitness_station", "Fitness Station"),
    ("leisure_garden", "Garden"),
    ("leisure_golf_course", "Golf Course"),
    ("leisure_horse_riding", "Horse Riding Centre"),
    ("leisure_ice_rink", "Ice Rink"),
    ("leisure", "Leisure"),
    ("leisure_marina", "Marina"),
    ("leisure_miniature_golf", "Miniature Golf"),
    ("leisure_nature_reserve", "Nature Reserve"),
    ("leisure_outdoor_seating", "Outdoor Seating"),
    ("leisure_park", "Park"),
    ("leisure_picnic_table", "Picnic Table"),
    ("leisure_pitch", "Sports Pitch"),
    ("leisure_playground", "Playground"),
    ("leisure_recreation_ground", "Recreation Ground"),
    ("leisure_resort", "Resort"),
    ("leisure_sauna", "Sauna"),
    ("leisure_slipway", "Slipway"),
    ("leisure_sports_centre", "Sports Centre"),
    ("leisure_stadium", "Stadium"),
    ("leisure_swimming_pool", "Swimming Pool"),
    ("leisure_track", "Running Track"),
    ("leisure_water_park", "Water Park"),
    ("lock", "Lock"),
    ("man_made_adit", "Adit"),
    ("man_made_advertising", "Advertising"),
    ("man_made_antenna", "Antenna"),
    ("man_made_avalanche_protection", "Avalanche Protection"),
    ("man_made_beacon", "Beacon"),
    ("man_made_beam", "Beam"),
    ("man_made_beehive", "Bee Hive"),
    ("man_made_breakwater", "Breakwater"),
    ("man_made_bridge", "Bridge"),
    ("man_made_bunker_silo", "Bunker"),
    ("man_made_cairn", "Cairn"),
    ("man_made_chimney", "Chimney"),
    ("man_made_clearcut", "Clearcut"),
    ("man_made_communications_tower", "Communications Tower"),
    ("man_made_crane", "Crane"),
    ("man_made_cross", "Cross"),
    ("man_made_dolphin", "Mooring Post"),
    ("man_made_dyke", "Dyke"),
    ("man_made_embankment", "Embankment"),
    ("man_made_flagpole", "Flagpole"),
    ("man_made_gasometer", "Gasometer"),
    ("man_made_groyne", "Groyne"),
    ("man_made_kiln", "Kiln"),
    ("man_made_lighthouse", "Lighthouse"),
    ("man_made_manhole", "Manhole"),
    ("man_made", "Man-made"),
    ("man_made_mast", "Mast"),
    ("man_made_mine", "Mine"),
    ("man_made_mineshaft", "Mine Shaft"),
    ("man_made_monitoring_station", "Monitoring Station"),
    ("man_made_petroleum_well", "Petroleum Well"),
    ("man_made_pier", "Pier"),
    ("man_made_pipeline", "Pipeline"),
    ("man_made_planter", "Planter"),
    ("man_made_pumping_station", "Pumping Station"),
    ("man_made_reservoir_covered", "Covered Reservoir"),
    ("man_made_silo", "Silo"),
    ("man_made_snow_cannon", "Snow Cannon"),
    ("man_made_snow_fence", "Snow Fence"),
    ("man_made_storage_tank", "Storage Tank"),
    ("man_made_street_cabinet", "Street Cabinet"),
    ("man_made_surveillance", "Surveillance"),
    ("man_made_telescope", "Telescope"),
    ("man_made_tower", "Tower"),
    ("man_made_utility_pole", "Utility Pole"),
    ("man_made_wastewater_plant", "Wastewater Plant"),
    ("man_made_watermill", "Water Mill"),
    ("man_made_water_tap", "Water Tap"),
    ("man_made_water_tower", "Water Tower"),
    ("man_made_water_well", "Well"),
    ("man_made_water_works", "Water Works"),
    ("man_made_windmill", "Wind Mill"),
    ("man_made_works", "Factory"),
    ("military_airfield", "Military Airfield"),
    ("military_barracks", "Barracks"),
    ("military_bunker", "Bunker"),
    ("military_checkpoint", "Checkpoint"),
    ("military", "Military"),
    ("military_trench", "Trench"),
    ("mountain_pass", "Mountain Pass"),
    ("natural_atoll", "Atoll"),
    ("natural_bare_rock", "Bare Rock"),
    ("natural_bay", "Bay"),
    ("natural_beach", "Beach"),
    ("natural_cape", "Cape"),
    ("natural_cave_entrance", "Cave Entrance"),
    ("natural_cliff", "Cliff"),
    ("natural_coastline", "Coastline"),
    ("natural_crater", "Crater"),
    ("natural_dune", "Dune"),
    ("natural_fell", "Fell"),
    ("natural_fjord", "Fjord"),
    ("natural_forest", "Forest"),
    ("natural_geyser", "Geyser"),
    ("natural_glacier", "Glacier"),
    ("natural_grassland", "Grassland"),
    ("natural_heath", "Heath"),
    ("natural_hill", "Hill"),
    ("natural_hot_spring", "Hot Spring"),
    ("natural_island", "Island"),
    ("natural_isthmus", "Isthmus"),
    ("natural_land", "Land"),
    ("natural_marsh", "Marsh"),
    ("natural_moor", "Moor"),
    ("natural_mud", "Mud"),
    ("natural", "Natural Feature"),
    ("natural_peak", "Peak"),
    ("natural_peninsula", "Peninsula"),
    ("natural_point", "Point"),
    ("natural_reef", "Reef"),
    ("natural_ridge", "Ridge"),
    ("natural_rock", "Rock"),
    ("natural_saddle", "Saddle"),
    ("natural_sand", "Sand"),
    ("natural_scree", "Scree"),
    ("natural_scrub", "Scrub"),
    ("natural_shingle", "Shingle"),
    ("natural_spring", "Spring"),
    ("natural_stone", "Stone"),
    ("natural_strait", "Strait"),
    ("natural_tree_row", "Tree Row"),
    ("natural_tree", "Tree"),
    ("natural_tundra", "Tundra"),
    ("natural_valley", "Valley"),
    ("natural_volcano", "Volcano"),
    ("natural_water", "Water"),
    ("natural_wetland", "Wetland"),
    ("natural_wood", "Wood"),
    ("office_accountant", "Accountant"),
    ("office_administrative", "Administration"),
    ("office_advertising_agency", "Advertising Agency"),
    ("office_architect", "Architect"),
    ("office_association", "Association"),
    ("office_company", "Company"),
    ("office_diplomatic", "Diplomatic Office"),
    ("office_educational_institution", "Educational Institution"),
    ("office_employment_agency", "Employment Agency"),
    ("office_energy_supplier", "Energy Supplier Office"),
    ("office_estate_agent", "Estate Agent"),
    ("office_financial", "Financial Office"),
    ("office_government", "Governmental Office"),
    ("office_insurance", "Insurance Office"),
    ("office_it", "IT Office"),
    ("office_lawyer", "Lawyer"),
    ("office_logistics", "Logistics Office"),
    ("office_newspaper", "Newspaper Office"),
    ("office_ngo", "NGO Office"),
    ("office_notary", "Notary"),
    ("office", "Office"),
    ("office_religion", "Religious Office"),
    ("office_research", "Research Office"),
    ("office_tax_advisor", "Tax Advisor"),
    ("office_telecommunication", "Telecommunication Office"),
    ("office_travel_agent", "Travel Agency"),
    ("place_allotments", "Allotments"),
    ("place_archipelago", "Archipelago"),
    ("place_city_block", "City Block"),
    ("place_city", "City"),
    ("place_country", "Country"),
    ("place_county", "County"),
    ("place_farm", "Farm"),
    ("place_hamlet", "Hamlet"),
    ("place_house", "House"),
    ("place_houses", "Houses"),
    ("place_island", "Island"),
    ("place_islet", "Islet"),
    ("place_isolated_dwelling", "Isolated Dwelling"),
    ("place_locality", "Locality"),
    ("place_municipality", "Municipality"),
    ("place_neighbourhood", "Neighbourhood"),
    ("place", "Place"),
    ("place_plot", "Plot"),
    ("place_postcode", "Postcode"),
    ("place_quarter", "Quarter"),
    ("place_region", "Region"),
    ("place_sea", "Sea"),
    ("place_square", "Square"),
    ("place_state", "State"),
    ("place_subdivision", "Subdivision"),
    ("place_suburb", "Suburb"),
    ("place_town", "Town"),
    ("place_village", "Village"),
    ("railway_abandoned", "Abandoned Railway"),
    ("railway_buffer_stop", "Buffer Stop"),
    ("railway_construction", "Railway under Construction"),
    ("railway_disused", "Disused Railway"),
    ("railway_funicular", "Funicular Railway"),
    ("railway_halt", "Train Stop"),
    ("railway_junction", "Railway Junction"),
    ("railway_level_crossing", "Level Crossing"),
    ("railway_light_rail", "Light Rail"),
    ("railway_miniature", "Miniature Rail"),
    ("railway_monorail", "Monorail"),
    ("railway_narrow_gauge", "Narrow Gauge Railway"),
    ("railway_platform", "Railway Platform"),
    ("railway_preserved", "Preserved Railway"),
    ("railway_proposed", "Proposed Railway"),
    ("railway_rail", "Rail"),
    ("railway_spur", "Railway Spur"),
    ("railway_station", "Railway Station"),
    ("railway_stop", "Railway Stop"),
    ("railway_subway_entrance", "Subway Entrance"),
    ("railway_subway", "Subway"),
    ("railway_switch", "Railway Points"),
    ("railway_tram_stop", "Tram Stop"),
    ("railway_tram", "Tramway"),
    ("railway_turntable", "Turntable"),
    ("railway_yard", "Railway Yard"),
    ("shop_agrarian", "Agrarian Shop"),
    ("shop_alcohol", "Off License"),
    ("shop_antiques", "Antiques"),
    ("shop_appliance", "Appliances Shop"),
    ("shop_art", "Art Shop"),
    ("shop_baby_goods", "Baby Goods"),
    ("shop_bag", "Bag Shop"),
    ("shop_bakery", "Bakery"),
    ("shop_bathroom_furnishing", "Bathroom Furnishing"),
    ("shop_beauty", "Beauty Shop"),
    ("shop_bed", "Bedding Products"),
    ("shop_beverages", "Beverages Shop"),
    ("shop_bicycle", "Bicycle Shop"),
    ("shop_bookmaker", "Bookmaker"),
    ("shop_books", "Book Shop"),
    ("shop_boutique", "Boutique"),
    ("shop_butcher", "Butcher"),
    ("shop_car", "Car Shop"),
    ("shop_car_parts", "Car Parts"),
    ("shop_carpet", "Carpet Shop"),
    ("shop_car_repair", "Car Repair"),
    ("shop_charity", "Charity Shop"),
    ("shop_cheese", "Cheese Shop"),
    ("shop_chemist", "Chemist"),
    ("shop_chocolate", "Chocolate"),
    ("shop_clothes", "Clothes Shop"),
    ("shop_coffee", "Coffee Shop"),
    ("shop_computer", "Computer Shop"),
    ("shop_confectionery", "Confectionery Shop"),
    ("shop_convenience", "Convenience Store"),
    ("shop_copyshop", "Copy Shop"),
    ("shop_cosmetics", "Cosmetics Shop"),
    ("shop_craft", "Crafts Supply Store"),
    ("shop_curtain", "Curtain Shop"),
    ("shop_dairy", "Dairy Shop"),
    ("shop_deli", "Deli"),
    ("shop_department_store", "Department Store"),
    ("shop_discount", "Discount Items Shop"),
    ("shop_doityourself", "Do-It-Yourself Shop"),
    ("shop_dry_cleaning", "Dry Cleaning"),
    ("shop_e-cigarette", "E-Cigarette Shop"),
    ("shop_electronics", "Electronics Shop"),
    ("shop_erotic", "Erotic Shop"),
    ("shop_estate_agent", "Estate Agent"),
    ("shop_fabric", "Fabric Store"),
    ("shop_farm", "Farm Shop"),
    ("shop_fashion", "Fashion Shop"),
    ("shop_fishing", "Fishing Supplies Shop"),
    ("shop_florist", "Florist"),
    ("shop_food", "Food Shop"),
    ("shop_frame", "Frame Shop"),
    ("shop_funeral_directors", "Funeral Directors"),
    ("shop_furniture", "Furniture"),
    ("shop_garden_centre", "Garden Centre"),
    ("shop_gas", "Gas Store"),
    ("shop_general", "General Store"),
    ("shop_gift", "Gift Shop"),
    ("shop_greengrocer", "Greengrocer"),
    ("shop_grocery", "Grocery Shop"),
    ("shop_hairdresser", "Hairdresser"),
    ("shop_hardware", "Hardware Store"),
    ("shop_health_food", "Health Food Store"),
    ("shop_hearing_aids", "Hearing Aids"),
    ("shop_herbalist", "Herbalist"),
    ("shop_hifi", "Hi-Fi Shop"),
    ("shop_houseware", "Houseware Shop"),
    ("shop_ice_cream", "Ice Cream Shop"),
    ("shop_interior_decoration", "Interior Decoration"),
    ("shop_jewelry", "Jewelry Shop"),
    ("shop_kiosk", "Kiosk Shop"),
    ("shop_kitchen", "Kitchen Shop"),
    ("shop_laundry", "Laundry"),
    ("shop_locksmith", "Locksmith"),
    ("shop_lottery", "Lottery"),
    ("shop_mall", "Mall"),
    ("shop_massage", "Massage"),
    ("shop_medical_supply", "Medical Supply Shop"),
    ("shop_mobile_phone", "Mobile Phone Shop"),
    ("shop_money_lender", "Money Lender"),
    ("shop_motorcycle", "Motorcycle Shop"),
    ("shop_motorcycle_repair", "Motorcycle Repair Shop"),
    ("shop_musical_instrument", "Musical Instruments"),
    ("shop_music", "Music Shop"),
    ("shop_newsagent", "Newsagent"),
    ("shop_nutrition_supplements", "Nutrition Supplements"),
    ("shop_optician", "Optician"),
    ("shop_organic", "Organic Food Shop"),
    ("shop_outdoor", "Outdoor Shop"),
    ("shop_paint", "Paint Shop"),
    ("shop_pastry", "Pastry Shop"),
    ("shop_pawnbroker", "Pawnbroker"),
    ("shop_perfumery", "Perfumery"),
    ("shop_pet_grooming", "Pet Grooming"),
    ("shop_pet", "Pet Shop"),
    ("shop_photo", "Photo Shop"),
    ("shop_seafood", "Sea Food"),
    ("shop_second_hand", "Second-hand Shop"),
    ("shop_sewing", "Sewing Shop"),
    ("shop_shoes", "Shoe Shop"),
    ("shop", "Shop"),
    ("shop_sports", "Sports Shop"),
    ("shop_stationery", "Stationery Shop"),
    ("shop_storage_rental", "Storage Rental"),
    ("shop_supermarket", "Supermarket"),
    ("shop_tailor", "Tailor"),
    ("shop_tattoo", "Tattoo Shop"),
    ("shop_tea", "Tea Shop"),
    ("shop_ticket", "Ticket Shop"),
    ("shop_tobacco", "Tobacco Shop"),
    ("shop_toys", "Toy Shop"),
    ("shop_travel_agency", "Travel Agency"),
    ("shop_tyres", "Tyre Shop"),
    ("shop_vacant", "Vacant Shop"),
    ("shop_variety_store", "Variety Store"),
    ("shop_video_games", "Video Game Store"),
    ("shop_video", "Video Shop"),
    ("shop_wholesale", "Wholesale Store"),
    ("shop_wine", "Wine Store"),
    ("tourism_alpine_hut", "Alpine Hut"),
    ("tourism_apartment", "Holiday Apartment"),
    ("tourism_artwork", "Artwork"),
    ("tourism_attraction", "Attraction"),
    ("tourism_bed_and_breakfast", "Bed and Breakfast"),
    ("tourism_cabin", "Tourist Cabin"),
    ("tourism_camp_pitch", "Camp Pitch"),
    ("tourism_camp_site", "Camp Site"),
    ("tourism_caravan_site", "Caravan Site"),
    ("tourism_chalet", "Chalet"),
    ("tourism_gallery", "Gallery"),
    ("tourism_guest_house", "Guest House"),
    ("tourism_hostel", "Hostel"),
    ("tourism_hotel", "Hotel"),
    ("tourism_information", "Information"),
    ("tourism_motel", "Motel"),
    ("tourism_museum", "Museum"),
    ("tourism_picnic_site", "Picnic Site"),
    ("tourism_theme_park", "Theme Park"),
    ("tourism_viewpoint", "Viewpoint"),
    ("tourism_wilderness_hut", "Wilderness Hut"),
    ("tourism_zoo", "Zoo"),
    ("tunnel_building_passage", "Building Passage"),
    ("tunnel_culvert", "Culvert"),
    ("tunnel", "Tunnel"),
    ("water_basin", "Water basin"),
    ("water_fishpond", "Fish Pond"),
    ("water_lagoon", "Lagoon"),
    ("water_lake", "Lake"),
    ("water_lock", "Lock"),
    ("water_oxbow", "Oxbow"),
    ("water_pond", "Pond"),
    ("water_reservoir", "Reservoir"),
    ("water_stream_pool", "Stream Pool"),
    ("water_wastewater", "Waste Water"),
    ("waterway_artificial", "Artificial Waterway"),
    ("waterway_boatyard", "Boatyard"),
    ("waterway_canal", "Canal"),
    ("waterway_dam", "Dam"),
    ("waterway_derelict_canal", "Derelict Canal"),
    ("waterway_ditch", "Ditch"),
    ("waterway_dock", "Dock"),
    ("waterway_drain", "Drain"),
    ("waterway_lock_gate", "Lock Gate"),
    ("waterway_lock", "Lock"),
    ("waterway_mooring", "Mooring"),
    ("waterway_rapids", "Rapids"),
    ("waterway_river", "River"),
    ("waterway_stream", "Stream"),
    ("waterway_wadi", "Wadi"),
    ("waterway_waterfall", "Waterfall"),
    ("waterway", "Waterway"),
    ("waterway_weir", "Weir"),
];
